export const APP_SIGN_IN_REQUEST = 'APP_SIGN_IN_REQUEST';
export const APP_SIGN_IN_SUCCESS = 'APP_SIGN_IN_SUCCESS';
export const APP_SIGN_IN_ERROR = 'APP_SIGN_IN_ERROR';

export const APP_LOG_OUT_REQUEST = 'APP_LOG_OUT_REQUEST';
